name: Deploy Storybook to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  build-and-publish:
    name: Build Storybook and publish to Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./

      - name: Build Storybook
        run: npm run build-storybook
        working-directory: ./

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload Storybook artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: build-storybook
